# Generated by Django 5.0.4 on 2024-05-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('cam_mark_returned', 'Set book as returned'),)},
        ),
    ]
